apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: rest-api-app
spec:
  replicas: 2
  selector: # how to find which pod to manage
    matchLabels:
      app: rest-api-app
  template: # it is a Pod object
    metadata: # give our pods some label so they can be found by deployment
      labels:
        app: rest-api-app
    spec:
      containers:
        - name: rest-api-app
          # image: api-app:2 # same as initial image - demo rollout
          image: api-app:ac74027 # initial image with no config
          env:
            - name: BACK_END_IP
              value: backend
          ports:
            - containerPort: 8080
---
# Volume Mount with Config Example - Comment above and comment out the below:
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: api
#   labels:
#     app: rest-api-app
# spec:
#   replicas: 2
#   selector: 
#     matchLabels:
#       app: rest-api-app
#   template: 
#     metadata:
#       labels:
#         app: rest-api-app
#     spec:
#       volumes:
#         - name: app-config
#           configMap:
#             name: rest-api-app
#             items:
#               - key: custom_greeting.js
#                 path: custom_greeting.js
#       containers:
#         - name: rest-api-app
#           image: api-app:9278fb7
#           env:
#             - name: BACK_END_IP
#               valueFrom:
#                 configMapKeyRef:
#                   name: rest-api-app
#                   key: BACK_END_IP
#           ports:
#             - containerPort: 8080
#           volumeMounts:
#             - name: app-config
#               mountPath: /usr/src/app/custom_scripts