apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-api-app
  labels:
    app: rest-api-app
data:
  custom_greeting.js: |-
    function Greeting() { 
      console.log('Hello, this is rest api app\n' + 'This is from ConfigMap') 
    }
    module.exports.Greeting = Greeting;
  BACKEND_IP: backend
  
  