apiVersion: v1
kind: Pod
metadata:
  name: rest-api-app  
  labels:
    app: rest-api-app
spec:
  containers:
    - name: rest-api-app
      image: binsabbar/k8s-training-api-app:1
      env:
        - name: BACKEND_IP
          # value: backend #the name of our service
          value: IP_OF_POD # the IP of the pod
      ports:
        - containerPort: 8080