apiVersion: v1
kind: Pod
metadata:
  name: arithmetic-operations-app #unique
  labels:
    app: backend # not unique
spec:
  containers:
    - name: arithmetic-operations-app
      image: binsabbar/k8s-training-backend-app:1
      ports:
        - containerPort: 8080