apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP # expose it within the cluser only
  ports: # create a service with port 8080, connect it to pod's port 8080
    - port: 8080
      targetPort: 8080
  selector: # select any pod that has this app label
    app: backend